module.exports = Object.freeze({
  CRON_TYPE_START: 'start',
  CRON_TYPE_STOP: 'stop',
  CRON_TYPE_POLLMAPS: 'pollmaps',

  PERMISSION_DENIED: 'Permission denied',
  COMMANDS: 'Commands',
  SERVER_STARTED: 'Server started',
  SERVER_STOPPED: 'Server stopped',
  MAPS_POLL: 'Maps poll',
  TOP_10: 'Top 10',
  FIRST_MAP: 'First Map',
  MAP_CYCLE: 'Map Cycle',
  ADDRESS: 'Address',
  PORT: 'Port',
  MAPS: 'Maps',

  COMMNAD_HELP: '/help',
  COMMAND_SERVER: /\/server (.+)/,
  COMMAND_POLL: /\/poll (.+)/,
  COMMAND_CRON: /\/cron (.+)/,
  COMMAND_SERVER_START: 'start',
  COMMAND_SERVER_STOP: 'stop',
  COMMAND_SERVER_TOP: 'top',
  COMMAND_SERVER_MAPS: 'maps',
  COMMAND_SERVER_INFO: 'info',
  COMMAND_SERVER_ADDRESS: 'address',
  COMMAND_SERVER_PORT: 'port',
  COMMAND_POLL_MAPS: 'maps',

  ON_MESSAGE: 'message',
  ON_POLL: 'poll',
  ON_POLLING_ERROR: 'polling_error',

  CREATOR: 'creator',
  ADMIN: 'administrator',
  PARSE_MODE: 'html',
});
