module.exports = Object.freeze({
  CRON_TYPE_START: 'start',
  CRON_TYPE_STOP: 'stop',
  CRON_TYPE_POLLMAPS: 'pollmaps',

  PERMISSION_DENIED: 'Permission denied',
  USER_UPDATED: 'User {{username}} updated',
  USER_NOT_FOUND: 'User {{username}} not found',
  USER_REGISTRED: 'User {{username}} registred or updated',
  USER_DELETED: 'User {{username}} deleted',
  COMMANDS: 'Commands',
  SERVER_STARTED: 'Server started',
  SERVER_STOPPED: 'Server stopped',
  PATH_NOT_FOUND: 'Path not found',
  NOT_CONFIGURED: 'Not configured',
  MAPS_POLL: 'Maps poll',
  TOP_10: 'Top 10',
  FIRST_MAP: 'First Map',
  MAP_CYCLE: 'Map Cycle',
  ADDRESS: 'Address',
  PORT: 'Port',
  MAPS: 'Maps',

  COMMNAD_HELP: '/help',
  COMMAND_USER: /\/user (.+)/,
  COMMAND_SERVER: /\/server (.+)/,
  COMMAND_POLL: /\/poll (.+)/,
  COMMAND_CRON: /\/cron (.+)/,
  COMMAND_USER_REGISTER: 'register',
  COMMAND_USER_DELETE: 'delete',
  COMMAND_USER_ADMIN: 'admin',
  COMMAND_SERVER_START: 'start',
  COMMAND_SERVER_STOP: 'stop',
  COMMAND_SERVER_TOP: 'top',
  COMMAND_SERVER_MAPS: 'maps',
  COMMAND_SERVER_INFO: 'info',
  COMMAND_SERVER_ADDRESS: 'address',
  COMMAND_SERVER_PORT: 'port',
  COMMAND_POLL_MAPS: 'maps',

  ON_MESSAGE: 'message',
  ON_POLL: 'poll',
  ON_POLLING_ERROR: 'polling_error',

  ROLE_CREATOR: 'creator',
  ROLE_ADMIN: 'admin',

  EXECUTABLE: 'hlds.exe',
  MAPS_EXTENSION: '.bsp',
  PARSE_MODE: 'html',
});
